version: "3"
services:
  smtp:
    image: rnwood/smtp4dev:v3
    ports:
      - "5000:80"
      - "25:25"
      - "143:143"
  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "pa55w0rd!"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"